{% set name = "pyvis" %}
{% set version = "2022-04-13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WestHealth/pyvis/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e5b99b043c3989564ea9106c3a74762131998d2e4bbcd489859a860c810ba062

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ipython >=5.3.0
    - jinja2 >=2.9.6
    - jsonpickle >=1.4.1
    - networkx >=1.11

test:
  imports:
    - pyvis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WestHealth/pyvis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE_BSD.txt
  summary: A Python network visualization library

extra:
  recipe-maintainers:
    - ocefpaf
